-- MySQL Script generated by MySQL Workbench
-- Wed Dec 29 21:45:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema paesws_nostroy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paesws_nostroy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paesws_nostroy` DEFAULT CHARACTER SET utf8 ;
USE `paesws_nostroy` ;

-- -----------------------------------------------------
-- Table `paesws_nostroy`.`personal_datas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paesws_nostroy`.`personal_datas` (
  `id_personal_datas` INT NOT NULL AUTO_INCREMENT,
  `personal_number` VARCHAR(45) NOT NULL,
  `FIO` VARCHAR(45) NOT NULL,
  `registration_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_personal_datas`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
